blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/maximyudayev/pysioviz/issues
    about: If your questions is not answered in the Issues tab, feel free to ask in our GitHub Discussions
